
query Members($namespaceId: ID, $page: Int, $length: PaginationLength) {
  members(filter: { 
    namespaceId: $namespaceId, 
    pagination: { page: $page, length: $length }
  }) {
    id
    userId
    username
    email
  }
}
