
query Members($namespaceId: ID, $page: Int, $length: FilterPaginationLengthEnum) {
  members(filter: {
    namespaceId: $namespaceId,
    filter: { pagination: { page: $page, length: $length } }
  }) {
    id
    userId
    username
    email
  }
}
