import type { TourConfig } from '@/composables/useOnboarding';

export const atraceTour: TourConfig = {
  id: 'atrace-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="atrace-title"]',
      titleKey: 'app.tourAtraceWelcomeTitle',
      contentKey: 'app.tourAtraceWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'create-post',
      target: [
        '[data-tour="create-post-btn"]',
        '[data-tour="create-post-btn-mobile"]',
        '[data-tour="create-post-btn-empty"]',
      ],
      titleKey: 'app.tourAtraceCreateTitle',
      contentKey: 'app.tourAtraceCreateContent',
      placement: 'left',
      highlightPadding: 12,
    },
    {
      id: 'posts-list',
      target: [
        '[data-tour="posts-list"]',
        '[data-tour="posts-list-mobile"]',
      ],
      titleKey: 'app.tourAtracePostsTitle',
      contentKey: 'app.tourAtracePostsContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
    {
      id: 'print-qr',
      target: '[data-tour="post-qr-btn"]',
      titleKey: 'app.tourAtracePrintQrTitle',
      contentKey: 'app.tourAtracePrintQrContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
    {
      id: 'attendance-table',
      target: '[data-tour="attendance-table"]',
      titleKey: 'app.tourAtraceTableTitle',
      contentKey: 'app.tourAtraceTableContent',
      placement: 'top',
      highlightPadding: 8,
    },
    {
      id: 'calculate',
      target: '[data-tour="calculate-btn"]',
      titleKey: 'app.tourAtraceCalculateTitle',
      contentKey: 'app.tourAtraceCalculateContent',
      placement: 'right',
      highlightPadding: 8,
    },
    {
      id: 'settings',
      target: '[data-tour="settings-btn"]',
      titleKey: 'app.tourAtraceSettingsTitle',
      contentKey: 'app.tourAtraceSettingsContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'help-button',
      target: '[data-tour="help-button"]',
      titleKey: 'app.tourAtraceHelpTitle',
      contentKey: 'app.tourAtraceHelpContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
  ],
};

export const menuTour: TourConfig = {
  id: 'menu-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="menu-title"]',
      titleKey: 'app.tourMenuWelcomeTitle',
      contentKey: 'app.tourMenuWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'create-order',
      target: '[data-tour="menu-create-btn"]',
      titleKey: 'app.tourMenuCreateTitle',
      contentKey: 'app.tourMenuCreateContent',
      placement: 'left',
      highlightPadding: 10,
    },
    {
      id: 'kitchen-board',
      target: '[data-tour="menu-kitchen-board-btn"]',
      titleKey: 'app.tourMenuKitchenTitle',
      contentKey: 'app.tourMenuKitchenContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'orders-table',
      target: '[data-tour="menu-orders-table"]',
      titleKey: 'app.tourMenuTableTitle',
      contentKey: 'app.tourMenuTableContent',
      placement: 'top',
      highlightPadding: 8,
    },
    {
      id: 'settings',
      target: '[data-tour="menu-settings-btn"]',
      titleKey: 'app.tourMenuSettingsTitle',
      contentKey: 'app.tourMenuSettingsContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'help-button',
      target: '[data-tour="help-button"]',
      titleKey: 'app.tourMenuHelpTitle',
      contentKey: 'app.tourMenuHelpContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
  ],
};

export const goodsTour: TourConfig = {
  id: 'goods-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="goods-warehouse-title"]',
      titleKey: 'goods.tourWelcomeTitle',
      contentKey: 'goods.tourWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'register',
      target: '[data-tour="goods-register-btn"]',
      titleKey: 'goods.tourRegisterTitle',
      contentKey: 'goods.tourRegisterContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'stock-table',
      target: '[data-tour="goods-stock-table"]',
      titleKey: 'goods.tourWarehouseTitle',
      contentKey: 'goods.tourWarehouseContent',
      placement: 'top',
      highlightPadding: 8,
    },
    {
      id: 'settings',
      target: '[data-tour="goods-settings-btn"]',
      titleKey: 'goods.tourSettingsTitle',
      contentKey: 'goods.tourSettingsContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'help-button',
      target: '[data-tour="help-button"]',
      titleKey: 'app.tourMenuHelpTitle',
      contentKey: 'app.tourMenuHelpContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
  ],
};

export const goodsRegisterTour: TourConfig = {
  id: 'goods-register-intro',
  steps: [
    {
      id: 'search',
      target: '[data-tour="goods-register-search"]',
      titleKey: 'goods.tourRegSearchTitle',
      contentKey: 'goods.tourRegSearchContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'products',
      target: '[data-tour="goods-register-products"]',
      titleKey: 'goods.tourRegProductsTitle',
      contentKey: 'goods.tourRegProductsContent',
      placement: 'right',
      highlightPadding: 8,
    },
    {
      id: 'cart',
      target: '[data-tour="goods-register-cart"]',
      titleKey: 'goods.tourRegCartTitle',
      contentKey: 'goods.tourRegCartContent',
      placement: 'left',
      highlightPadding: 8,
    },
    {
      id: 'shift-actions',
      target: '[data-tour="goods-register-shift-actions"]',
      titleKey: 'goods.tourRegShiftTitle',
      contentKey: 'goods.tourRegShiftContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
  ],
};

export const issuesTour: TourConfig = {
  id: 'issues-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="issues-title"]',
      titleKey: 'app.tourIssuesWelcomeTitle',
      contentKey: 'app.tourIssuesWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'create-issue',
      target: '[data-tour="issues-create-btn"]',
      titleKey: 'app.tourIssuesCreateTitle',
      contentKey: 'app.tourIssuesCreateContent',
      placement: 'left',
      highlightPadding: 10,
    },
    {
      id: 'board',
      target: '[data-tour="issues-board"]',
      titleKey: 'app.tourIssuesBoardTitle',
      contentKey: 'app.tourIssuesBoardContent',
      placement: 'top',
      highlightPadding: 8,
    },
    {
      id: 'settings',
      target: '[data-tour="issues-settings-btn"]',
      titleKey: 'app.tourIssuesSettingsTitle',
      contentKey: 'app.tourIssuesSettingsContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'help-button',
      target: '[data-tour="help-button"]',
      titleKey: 'app.tourIssuesHelpTitle',
      contentKey: 'app.tourIssuesHelpContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
  ],
};

export const contactsTour: TourConfig = {
  id: 'contacts-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="contacts-title"]',
      titleKey: 'app.tourContactsWelcomeTitle',
      contentKey: 'app.tourContactsWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'type-filter',
      target: '[data-tour="contacts-type-filter"]',
      titleKey: 'app.tourContactsFilterTitle',
      contentKey: 'app.tourContactsFilterContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'create-client',
      target: [
        '[data-tour="contacts-create-btn"]',
        '[data-tour="contacts-create-empty"]',
      ],
      titleKey: 'app.tourContactsCreateTitle',
      contentKey: 'app.tourContactsCreateContent',
      placement: 'left',
      highlightPadding: 10,
    },
    {
      id: 'clients-table',
      target: [
        '[data-tour="contacts-table-search"]',
        '[data-tour="contacts-table"]',
        '[data-tour="contacts-empty-state"]',
      ],
      titleKey: 'app.tourContactsTableTitle',
      contentKey: 'app.tourContactsTableContent',
      placement: 'top',
      highlightPadding: 8,
    },
    {
      id: 'settings',
      target: '[data-tour="contacts-settings-btn"]',
      titleKey: 'app.tourContactsSettingsTitle',
      contentKey: 'app.tourContactsSettingsContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'help-button',
      target: '[data-tour="help-button"]',
      titleKey: 'app.tourContactsHelpTitle',
      contentKey: 'app.tourContactsHelpContent',
      placement: 'bottom',
      highlightPadding: 8,
    },
  ],
};

export const peopleTour: TourConfig = {
  id: 'people-intro',
  steps: [
    {
      id: 'welcome',
      target: '[data-tour="people-title"]',
      titleKey: 'app.tourPeopleWelcomeTitle',
      contentKey: 'app.tourPeopleWelcomeContent',
      placement: 'bottom',
      highlightPadding: 12,
    },
    {
      id: 'add-bar',
      target: '[data-tour="people-add-bar"]',
      titleKey: 'app.tourPeopleAddBarTitle',
      contentKey: 'app.tourPeopleAddBarContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
    {
      id: 'team',
      target: '[data-tour="people-team"]',
      titleKey: 'app.tourPeopleTeamTitle',
      contentKey: 'app.tourPeopleTeamContent',
      placement: 'right',
      highlightPadding: 10,
    },
    {
      id: 'friends',
      target: '[data-tour="people-friends"]',
      titleKey: 'app.tourPeopleFriendsTitle',
      contentKey: 'app.tourPeopleFriendsContent',
      placement: 'left',
      highlightPadding: 10,
    },
    {
      id: 'referral',
      target: '[data-tour="people-referral"]',
      titleKey: 'app.tourPeopleReferralTitle',
      contentKey: 'app.tourPeopleReferralContent',
      placement: 'bottom',
      highlightPadding: 10,
    },
  ],
};
