query CatalogBusinesses(
  $categoryId: ID
  $tagId: ID
  $namespaceSlug: String
  $search: String
  $page: Int
  $length: FilterPaginationLengthEnum
) {
  catalogBusinesses(
    filter: {
      categoryId: $categoryId
      tagId: $tagId
      namespaceSlug: $namespaceSlug
      data: { search: $search, pagination: { page: $page, length: $length } }
    }
  ) {
    rows {
      id
      namespaceSlug
      sourceBranchId
      categoryId
      name
      logoUrl
      description
      address
      city
      lat
      lng
      isActive
    }
    info {
      count
    }
  }
}
