query MyFriends($status: FriendshipStatus) {
  myFriends(filter: { status: $status }) {
    rows {
      id
      status
      friend {
        id
        username
        email
      }
    }
    info { count }
  }
}