name: Actualize Remote Manifest & Deploy

on:
  push:
    branches: [ "main", "dev" ]
    tags: [ 'v*.*.*' ]

jobs:
  update-state:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout service repo
        uses: actions/checkout@v4

      - name: Update state repo
        uses: pieceowater-dev/lotof.cloud.ci/.github/actions/update-state@main
        with:
          repo-name: ${{ github.event.repository.name }}
          commit-sha: ${{ github.sha }}
          branch: ${{ github.ref_name }}
          ssh-key: ${{ secrets.STATE_REPO_SSH_KEY }}
